---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: "13.7.16"

verifier:
  name: inspec

platforms:
  - name: bento/ubuntu-16.04
  - name: bento/debian-8
  - name: bento/debian-9
  - name: bento/centos-6
  - name: bento/centos-7
  - name: bento/fedora-26
  - name: bento/fedora-27

suites:
  - name: default
    run_list:
      - recipe[rubygems-update-test::install-ruby]
      - recipe[rubygems-update::default]
